# Generated by Django 5.1.7 on 2025-05-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='discount_amount',
        ),
    ]
