# Generated by Django 5.1.7 on 2025-05-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('gcash', 'GCash')], default='cod', max_length=20),
        ),
    ]
