# Generated by Django 5.1.7 on 2025-05-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_passwordresetcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
