# Generated by Django 5.1.7 on 2025-06-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_address_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone_number',
        ),
    ]
