# Generated by Django 5.1.7 on 2025-05-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='full_description',
        ),
    ]
