# Generated by Django 5.1.7 on 2025-05-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_full_description_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
