# Generated by Django 5.1.7 on 2025-05-29 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
